import { TaskMeta } from 'vitest';
import { ProcessOutput } from 'zx';

declare module 'vitest' {

    // The runner adds metadata to the Vitest output in each test,
    // so we extend the type definition to include those fields:
    interface TaskMeta extends TestMeta {

    }
}

export type TestMeta = {
    description?: string;
    maxScore?: number;
    score?: number;
    logs?: {
        command: string;
        ok: boolean;

        stdout?: string;
        stderr?: string;
    }[];
}

export type RunLog = NonNullable<TestMeta["logs"]>[number];


export namespace ClassroomJSON {
    /**
     * The format for the result.json file that the autograder
     * will output, as per the Classroom 50 contract.
     * See https://github.com/foundation50/classroom50/wiki/Autograders#the-resultjson-contract
     */
    export type ClassroomReport = ClassroomAutograding & ClassroomEnvironment;

    /**
     * Environment variables injected by Classroom 50 from GitHub actions.
     */
    export type ClassroomEnvironment = {
        schema: string,
        classroom: string,
        assignment: string,
        usernames: string[],
        submission: string,
        commit: string,
        release: string,
        review: string,
        datetime: string
    };

    /**
     * Grading results, generated by the runner.ts script and converted
     * to the expected format by the reporter.ts script.
     */
    export type ClassroomAutograding = {
        'score': number;
        'max-score': number;
        'tests': ClassroomTest[];
    };

    /**
     * A single test case in the classroom autograding report. ClassroomTests
     * correspond to VitestAssertion, with the addition of scoring fields.
     */
    export type ClassroomTest = {
        'test-name': string;
        'passed': boolean;
        'score': number;
        'max-score': number;
    };
}

/**
 * Fields prefixed with $ are commands that are run on the terminal. By default,
 * all commands are expected to succeed with an exit code of 0.
 */
export namespace AutogradingTests {

    /**
     * Test suite is a collection of test commands and configuration options
     * that can be executed with the Vitest test runner.
     *
     * The test suite extends basic test cases with additional grading and logging
     * related features, which are used by the JSON and Markdown reporters to
     * generate their outputs.
     */
    export type TestSuite = {
        /** The working directory for all commands. If not specified, the current working directory of the process is used. */
        cwd?: string;

        /** Timeout for a test case or a lifecycle hook */
        defaultTimeout: Timeout;

        /** Default score for a single test case */
        defaultScore: number;

        name: string,
        description: string,

        beforeAll?: Runnable | Runnable[];
        beforeEach?: Runnable | Runnable[];
        afterEach?: Runnable | Runnable[];
        afterAll?: Runnable | Runnable[];
        tests: TestCase[];
    }

    /** Timeout with a number and unit. */
    type Timeout = { seconds: number } | { minutes: number };

    /** A runnable can be given either as a shell command, an object or a JS function. */
    export type Runnable = string | RunnableObj | Hook;

    export type RunnableObj = {
        name: string;
        $run: string;
        timeout?: Timeout;
    }

    export type Hook = (context: ExecutionContext) => Promise<any> | void;


    export type TestCase = RunnableObj & {
        description: string;
        $setup?: string;
        score?: number;

        /** A string or array of strings that the output must contain for the test to pass. */
        contains?: string | string[];

        /** A string or array of strings that the output must not contain. */
        notContains?: string | string[];

        /** The command to run for comparison against. The test passes if the output of the test matches the output of this command. */
        $compareRun?: Runnable;

        /**
         * A custom grader function that receives the test context and returns the scores awarded. For the
         * custom grader to be invoked, other all other checks must pass and the setup and run commands
         * must execute successfully.
         *
         * Any operations including addiotional commands or assertins can be invoked within the custom grader.
         * If the test should be failed, the grader should throw an error. Vitest `expect` assertions are
         * recommended for throwing errors, as they will be consistent with the rest of the checks.
         */
        customGrader?: (context: TestContext & { logs: RunLog[] }) => Promise<Pick<TaskMeta, 'score'>>;
    }

    /**
     * Tests run within a specific working directory and have specific environment variables available to them.
     * Passing the context to the hooks in suite setup allows them to run commands within the same environment
     * as the tests.
     */
    export type ExecutionContext = {
        /** Runs the given command using a configured environment and working directory. */
        runCmd: (cmd: string, logs: TaskMeta["logs"]) => Promise<ProcessOutput>,

        /** The test suite, for dynamically referencing fields. */
        testSuite: TestSuite
    }

    export type TestContext = ExecutionContext & {
        /** Logs for inspecting the test execution and for adding new entries. */
        logs: TaskMeta["logs"],

        /** The test case itself, for dynamically referencing fields. */
        testCase: TestCase
    }
}
