name: Autograding

on:
  push:

permissions:
  contents: read
  statuses: write

jobs:
  grade:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}

    steps:
      - uses: actions/checkout@v7

      - name: Set up Node.js
        uses: actions/setup-node@v7
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: |
          npm run build
          chmod +x dist/cli.js

      - name: Run the autograding action in the current repository
        uses: ./
        with:
          test_suite: ./exampleSuite.json
