name: Autograding

on:
  push:

permissions:
  contents: read
  statuses: write

jobs:
  grade:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - name: Set up Node.js
        uses: actions/setup-node@v7
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci
        timeout-minutes: 1

      - name: Test with Vitest
        run: npm test
        timeout-minutes: 1

      - name: Build
        timeout-minutes: 1
        run: |
          npm run build
          chmod +x dist/cli.js

      - name: Run the autograding action in the current repository
        uses: ./
        timeout-minutes: 1
        with:
          test_suite: ./exampleSuite.json
